sexes = {
    "M": "mare",
    "H": "horse",
    "G": "gelding",
    "C": "colt",
    "F": "filly"
}

colors = {
    "gr": "gray",
    "b": "bay",
    "ch": "chesnut",
    "dkb/br": "dark bay/brown",
    "gr/r": "gray/roan",
    "pal": "palomino",
    "br": "brown",
    "blk": "black",
    "blk/br": "black/brown",
    "buck": "buckskin",
    "ro": "roan",
}

countries = {
    "ARG": "Argentina",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BHR": "Bahrain",
    "BAR": "Barbados",
    "BEL": "Belgium",
    "BOS": "Bosnia",
    "BRZ": "Brazil",
    "BUL": "Bulgaria",
    "CAN": "Canada",
    "CHI": "Chile",
    "CHN": "China",
    "COL": "Columbia",
    "CRO": "Croatia",
    "CYP": "Cyprus",
    "CZE": "The Czech Republic",
    "DR": "The Dominican Republic",
    "ECU": "Ecuador",
    "FIN": "Finland",
    "FR": "France",
    "GER": "Germany",
    "GB": "Great Britain",
    "GR": "Greece",
    "GDR": "East Germany",
    "HER": "Herzegovina",
    "HUN": "Hungary",
    "IND": "India",
    "IRE": "Ireland",
    "IRN": "Iran",
    "ITY": "Italy",
    "JAM": "Jamacia",
    "JPN": "Japan",
    "KEN": "Kenya",
    "KOR": "Korea",
    "LEB": "Lebanon",
    "LTU": "Lithuania",
    "LUX": "Luxemburg",
    "MAL": "Malaysia",
    "MEX": "Mexico",
    "MOR": "Morocco",
    "HOL": "The Netherlands",
    "NZ": "New Zealand",
    "NOR": "Norway",
    "OM": "Oman",
    "PAK": "Pakistan",
    "PRY": "Paraguay",
    "PER": "Peru",
    "PHI": "Philippines",
    "POL": "Poland",
    "POR": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RUM": "Romania",
    "RUS": "Russia",
    "KSA": "Saudi Arabia",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SAF": "South Africa",
    "SPA": "Spain",
    "SWE": "Sweden",
    "SWI": "Switzerland",
    "SY": "Syria",
    "TRI": "Trinidad and Tabago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "UAE": "The United Arab Emirates",
    "URU": "Uruguay",
    "USA": "The United States",
    "UZB": "Uzbekistan",
    "VEN": "Venezuela",
    "ZIM": "Zimbabwe"
}
